## YAML Template.
---
management:
   endpoints:
      web:
         exposure:
            include: "*"
health:
   indicator: 
      enabled: true 
spring:
   data:      
      mongodb.host: localhost
      mongodb.port: 27017
      mongodb.uri: mongodb://localhost/test
      
